<?php

namespace App\Exceptions;

use Illuminate\Foundation\Exceptions\Handler as ExceptionHandler;
use Throwable;

class Handler extends ExceptionHandler
{
    /**
     * The list of the inputs that are never flashed to the session on validation exceptions.
     *
     * @var array<int, string>
     */
    protected $dontFlash = [
        'current_password',
        'password',
        'password_confirmation',
    ];

    /**
     * Register the exception handling callbacks for the application.
     */
    public function register(): void
    {
        $this->reportable(function (Throwable $e) {
            //
        });
    }

    public function render($request, Throwable $e)
    {
        if ($request->expectsJson()) {
            // Return a JSON response for API requests
            return response()->json([
                'status' => false,
                'data' => null,
                'msg' => $e->getMessage(),
            ]);
//            return new JsonResponse(, $this->isHttpException($exception) ? $exception->getStatusCode() : 500);
        }
        return parent::render($request, $e); // TODO: Change the autogenerated stub
    }
}
